// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASigmBqJJSOkIBCVuxDtbLSaWQFy6Q_hw',
    appId: '1:572401094221:web:d3c9ecb72b86fa06439604',
    messagingSenderId: '572401094221',
    projectId: 'updated-yumm',
    authDomain: 'updated-yumm.firebaseapp.com',
    storageBucket: 'updated-yumm.firebasestorage.app',
    measurementId: 'G-KQ3YKXG4BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgDsy7ETgdNrTGKtGXPw5AKck19oY7Vz8',
    appId: '1:572401094221:android:5c59990dd3c88736439604',
    messagingSenderId: '572401094221',
    projectId: 'updated-yumm',
    storageBucket: 'updated-yumm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFPCrTeVh9wm77gJjPLVeO8tM-L5vM0M',
    appId: '1:572401094221:ios:bcb7660bc507cd38439604',
    messagingSenderId: '572401094221',
    projectId: 'updated-yumm',
    storageBucket: 'updated-yumm.firebasestorage.app',
    iosBundleId: 'com.example.yumm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFPCrTeVh9wm77gJjPLVeO8tM-L5vM0M',
    appId: '1:572401094221:ios:bcb7660bc507cd38439604',
    messagingSenderId: '572401094221',
    projectId: 'updated-yumm',
    storageBucket: 'updated-yumm.firebasestorage.app',
    iosBundleId: 'com.example.yumm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASigmBqJJSOkIBCVuxDtbLSaWQFy6Q_hw',
    appId: '1:572401094221:web:7af6ea02ec11e6ce439604',
    messagingSenderId: '572401094221',
    projectId: 'updated-yumm',
    authDomain: 'updated-yumm.firebaseapp.com',
    storageBucket: 'updated-yumm.firebasestorage.app',
    measurementId: 'G-023J7NDM0W',
  );
}
